services:
  homepage:
    container_name: homepage-latest
    image: abambah/homepage2:latest
    # image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /root/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: /root/homepage/.env
    hostname: homepage
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
