---
- Hypervisor:
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: pve1
        siteMonitor: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          cache: 300000
          refreshInterval: 60000
          node: pve
    - Proxmox2:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL_2}}"
        description: pve-dell
        siteMonitor: "{{HOMEPAGE_VAR_PROXMOX_URL_2}}"
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL_2}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER_2}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY_2}}"
          cache: 300000
          refreshInterval: 60000
          node: pve2
    - Proxmox3:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL_3}}"
        description: pve-backup
        siteMonitor: "{{HOMEPAGE_VAR_PROXMOX_URL_3}}"
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL_3}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER_3}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY_3}}"
          cache: 300000
          refreshInterval: 60000
          node: pve-backup
    - Proxmox4:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: pve6
        siteMonitor: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          cache: 300000
          refreshInterval: 60000
          node: pve6

- DNS:
    - cloudflare:
        icon: cloudflare.svg
        href: https://dash.cloudflare.com/
        description: Cloudflare
        siteMonitor: https://dash.cloudflare.com/
        widget:
          type: cloudflared
          accountid: "{{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}"
          key: "{{HOMEPAGE_VAR_CLOUDFLARE_API_KEY}}"
          tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}}"
          cache: 300000
          refreshInterval: 60000
    - Pi-Hole1:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}/admin"
        description: orange-pi-hole
        siteMonitor: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}/admin"
        widget:
          type: pihole
          url: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_1}}"
          version: 6
          cache: 300000
          refreshInterval: 60000
    - Pi-Hole2:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}/admin"
        siteMonitor: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}/admin"
        description: proxmox-lxc-128
        widget:
          type: pihole
          url: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_2}}"
          version: 6
          cache: 300000
          refreshInterval: 60000
    - Pi-Hole3:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE_URL_3}}/admin"
        siteMonitor: "{{HOMEPAGE_VAR_PIHOLE_URL_3}}/admin"
        description: pve-3-pihole-unbound
        widget:
          type: pihole
          url: "{{HOMEPAGE_VAR_PIHOLE_URL_3}}"
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_3}}"
          version: 6
          cache: 300000
          refreshInterval: 60000
    - Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin/machines
        description: VPN mesh network
        widget:
          type: tailscale
          deviceid: "{{HOMEPAGE_VAR_TAILSCALE_DEVICE_ID}}"
          key: "{{HOMEPAGE_VAR_TAILSCALE_API_KEY}}"
          cache: 300000
          refreshInterval: 60000

- Storage-Server:
    - Unraid:
        href: https://unraid.asbblog.com/login/
        description: Unraid
        siteMonitor: https://unraid.asbblog.com/login
        icon: unraid
    - Synology:
        href: https://192-168-68-80.abambah.direct.quickconnect.to:5001/#/signin/
        description: synology
        siteMonitor: https://192-168-68-80.abambah.direct.quickconnect.to:5001/#/signin/
        icon: si-synology
    - TrueNas:
        href: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
        description: scale
        siteMonitor: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
        icon: truenas.svg
        widget:
          type: truenas
          url: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
          key: "{{HOMEPAGE_VAR_TRUENAS_PASSWORD}}"
          cache: 300000
          refreshInterval: 60000

- Other:
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: sunday
          view: monthly
          maxEvents: 10
          showTime: true
          timezone: America/Los_Angeles
          integrations:
            - type: sonarr
              service_group: Media
              service_name: Sonarr
              color: teal
            - type: radarr
              service_group: Media
              service_name: Radarr
              color: red
            - type: lidarr
              service_group: Media2
              service_name: lidarr
              color: blue
            - type: readarr
              service_group: Media
              service_name: readarr
              color: purple
            - type: ical
              name: Coursera
              color: zinc
              url: http://www.coursera.org/api/learnerCalendars.v1/46974119/uRHz9JWGSM2swl2Uux8vHg.ics
              params:
                showName: true